package com.paypal.adaptive.core.accounts;

public enum CountryCode {
    AX("ÅLAND ISLANDS"),
    AL("ALBANIA"),
    DZ("ALGERIA"),
    AS("AMERICAN SAMOA"),
    AD("ANDORRA"),
    AI("ANGUILLA"),
    AQ("ANTARCTICA"),
    AG("ANTIGUA AND BARBUDA"),
    AR("ARGENTINA"),
    AM("ARMENIA"),
    AW("ARUBA"),
    AU("AUSTRALIA"),
    AT("AUSTRIA"),
    BS("BAHAMAS"),
    BH("BAHRAIN"),
    BB("BARBADOS"),
    BE("BELGIUM"),
    BZ("BELIZE"),
    BJ("BENIN"),
    BM("BERMUDA"),
    BT("BHUTAN"),
    BW("BOTSWANA"),
    BV("BOUVET ISLAND"),
    BR("BRAZIL"),
    IO("BRITISH INDIAN OCEAN TERRITORY"),
    BN("BRUNEI DARUSSALAM"),
    BG("BULGARIA"),
    BF("BURKINA FASO"),
    CA("CANADA"),
    CV("CAPE VERDE"),
    KY("CAYMAN ISLANDS"),
    CF("CENTRAL AFRICAN REPUBLIC"),
    CL("CHILE"),
    CN("CHINA"),
    CX("CHRISTMAS ISLAND"),
    CC("COCOS (KEELING) ISLANDS"),
    CO("COLOMBIA"),
    CK("COOK ISLANDS"),
    CR("COSTA RICA"),
    CY("CYPRUS"),
    CZ("CZECH REPUBLIC"),
    DK("DENMARK"),
    DJ("DJIBOUTI"),
    DM("DOMINICA"),
    DO("DOMINICAN REPUBLIC"),
    EG("EGYPT"),
    SV("EL SALVADOR"),
    EE("ESTONIA"),
    FK("FALKLAND ISLANDS (MALVINAS)"),
    FO("FAROE ISLANDS"),
    FJ("FIJI"),
    FI("FINLAND"),
    FR("FRANCE"),
    GF("FRENCH GUIANA"),
    PF("FRENCH POLYNESIA"),
    TF("FRENCH SOUTHERN TERRITORIES"),
    GM("GAMBIA"),
    GE("GEORGIA"),
    DE("GERMANY"),
    GH("GHANA"),
    GI("GIBRALTAR"),
    GR("GREECE"),
    GL("GREENLAND"),
    GD("GRENADA"),
    GP("GUADELOUPE"),
    GU("GUAM"),
    HM("HEARD ISLAND AND MCDONALD ISLANDS"),
    VA("HOLY SEE (VATICAN CITY STATE)"),
    HN("HONDURAS"),
    HK("HONG KONG"),
    HU("HUNGARY"),
    IS("ICELAND"),
    IN("INDIA"),
    ID("INDONESIA"),
    IE("IRELAND"),
    IM("ISLE OF MAN"),
    IL("ISRAEL"),
    IT("ITALY"),
    JM("JAMAICA"),
    JP("JAPAN"),
    JO("JORDAN"),
    KZ("KAZAKHSTAN"),
    KI("KIRIBATI"),
    KR("KOREA, REPUBLIC OF"),
    KW("KUWAIT"),
    KG("KYRGYZSTAN"),
    LV("LATVIA"),
    LS("LESOTHO"),
    LI("LIECHTENSTEIN"),
    LT("LITHUANIA"),
    LU("LUXEMBOURG"),
    MO("MACAO"),
    MW("MALAWI"),
    MY("MALAYSIA"),
    MT("MALTA"),
    MH("MARSHALL ISLANDS"),
    MQ("MARTINIQUE"),
    MR("MAURITANIA"),
    MU("MAURITIUS"),
    YT("MAYOTTE"),
    MX("MEXICO"),
    FM("MICRONESIA, FEDERATED STATES OF"),
    MD("MOLDOVA, REPUBLIC OF"),
    MC("MONACO"),
    MN("MONGOLIA"),
    MS("MONTSERRAT"),
    MA("MOROCCO"),
    MZ("MOZAMBIQUE"),
    NA("NAMIBIA"),
    NR("NAURU"),
    NP("NEPAL"),
    NL("NETHERLANDS"),
    AN("NETHERLANDS ANTILLES"),
    NC("NEW CALEDONIA"),
    NZ("NEW ZEALAND"),
    NI("NICARAGUA"),
    NE("NIGER"),
    NU("NIUE"),
    NF("NORFOLK ISLAND"),
    MP("NORTHERN MARIANA ISLANDS"),
    NO("NORWAY"),
    OM("OMAN"),
    PW("PALAU"),
    PA("PANAMA"),
    PY("PARAGUAY"),
    PE("PERU"),
    PH("PHILIPPINES"),
    PN("PITCAIRN"),
    PL("POLAND"),
    PT("PORTUGAL"),
    PR("PUERTO RICO"),
    QA("QATAR"),
    RE("REUNION"),
    RO("ROMANIA"),
    SH("SAINT HELENA"),
    KN("SAINT KITTS AND NEVIS"),
    LC("SAINT LUCIA"),
    PM("SAINT PIERRE AND MIQUELON"),
    VC("SAINT VINCENT AND THE GRENADINES"),
    WS("SAMOA"),
    SM("SAN MARINO"),
    ST("SAO TOME AND PRINCIPE"),
    SA("SAUDI ARABIA"),
    SN("SENEGAL"),
    SC("SEYCHELLES"),
    SG("SINGAPORE"),
    SK("SLOVAKIA"),
    SI("SLOVENIA"),
    SB("SOLOMON ISLANDS"),
    ZA("SOUTH AFRICA"),
    GS("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
    ES("SPAIN"),
    SR("SURINAME"),
    SJ("SVALBARD AND JAN MAYEN"),
    SZ("SWAZILAND"),
    SE("SWEDEN"),
    CH("SWITZERLAND"),
    TW("TAIWAN, PROVINCE OF CHINA"),
    TZ("TANZANIA, UNITED REPUBLIC OF"),
    TH("THAILAND"),
    TK("TOKELAU"),
    TO("TONGA"),
    TT("TRINIDAD AND TOBAGO"),
    TN("TUNISIA"),
    TR("TURKEY"),
    TC("TURKS AND CAICOS ISLANDS"),
    TV("TUVALU"),
    UA("UKRAINE"),
    AE("UNITED ARAB EMIRATES"),
    GB("UNITED KINGDOM"),
    US("UNITED STATES"),
    UM("UNITED STATES MINOR OUTLYING ISLANDS"),
    UY("URUGUAY"),
    VN("VIET NAM"),
    VG("VIRGIN ISLANDS, BRITISH"),
    VI("VIRGIN ISLANDS, U.S."),
    WF("WALLIS AND FUTUNA"),
    ZM("ZAMBIA");
    
    private String country;
    
    CountryCode(String country) {
        this.country = country;
    }
    
    public String getCountry() {
        return country;
    }
 
    public static CountryCode fromValue(String value) {
        return valueOf(value.toUpperCase());
    }
}
